channels:
- conda-forge
- defaults
dependencies:
- pip=23.0.1
- python>=3.10
- numpy=1.24.2
- pip:
  - notebook==6.5.3
  - pandas==1.5.3
  - pytest==7.2.2
  - pre-commit==3.1.1
  - openai==0.27.1
  - pinecone-client==2.2.1
  - tiktoken==0.3.0
  - pytest-cov==4.0.0
  - pylint==2.17.0
  - pylint-quotes==0.2.3
  - pycodestyle==2.10.0
  - pydocstyle==6.3.0

