name: Build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    defaults:
      run:
        shell: bash -el {0}
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build mamba environment
      uses: conda-incubator/setup-miniconda@v2
      with:
          mamba-version: '*'
          activate-environment: ./env
          environment-file: environment.yml
          use-mamba: true
          python-version: '3.10'
    - name: Run tests and pre-commit checks
      run: make check
    - name: Gitleaks
      uses: gitleaks/gitleaks-action@v2.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
