name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build-mamba-environment
      uses: conda-incubator/setup-miniconda@v2
      with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: env
          environment-file: environment.yml

    - name: Run checks
      run: make check
