name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: provision-with-micromamba
      uses: mamba-org/provision-with-micromamba@v15
      with:
          environment-file: false
          environment-name: false


    - name: Run build
      run: make build
