name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
          mamba-version: "*"
          channel-priority: true
          activate-environment: env
          environment-file: environment.yml
          use-only-tar-bz2: true
          use-mamba: true
    - shell: bash -el {0}
    - name: run-tests
      run: make test
