name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: provision-with-micromamba
      uses: mamba-org/provision-with-micromamba@v15
      with:
          environment-file: environment.yaml
          environment-name: env
          extra-specs: |
            python=3.10


    - name: Run build
      run: make build
